[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2018"

[lib]
name = "mandelbrot_lib"
path = "src/lib.rs"

[[bin]]
name = "mandelbrot"
path = "src/bin.rs"

[dependencies]
image = "0.23"
num = "0.4"
crossbeam = "0.8"
rayon = "1.5"
